sudo: required
language: minimal
services:
  - docker

before_script:
  - echo "${DOCKER_PASSWORD}" | docker login --username gruen --password-stdin
  
script:
  - make lint
  - make build
  - make test
  - make push
